on:
  push:
    branches:
      - develop

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      releases_created: ${{ steps.release-please.outputs.releases_created }}
      tag_name: ${{ steps.release-please.outputs.tag_name }}
    steps:
      - id: release-please
        uses: google-github-actions/release-please-action@v3
        with:
          release-type: node
          package-name: flags
  deploy:
    runs-on: ubuntu-latest
    needs: release-please
    if: needs.release-please.outputs.releases_created
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ needs.release-please.outputs.tag_name }}
      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: npm
      - run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - run: npm install
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      # - run: git add -f *.js *.d.ts *.js.map
      # - run: |
      #     git commit -n -m "chore: release ${{ needs.release-please.outputs.tag_name }}"
      # - run: git tag build-${{ needs.release-please.outputs.tag_name }}
      # - run: git push origin build-${{ needs.release-please.outputs.tag_name }}
